### PR TITLE
Add php support

### PR DESCRIPTION
**Pull request by gbprod**
This commit introduce simple php support.
I will try to improve it step by step.

### CODE REVIEW

**Comment by SmiteshP** [comment]
Great! Let me know when its ready to be merged :)

**Comment by gbprod** [comment]
I've made some improvements, I think this could be merged

**Comment by SmiteshP** [comment]
Hey! before I merge this, could you share some screenshot or code snippet of each query working? That would help me in future by providing a reference point 😄

**Comment by gbprod** [comment]
Made some screenshots, is it ok for you ?

2022-01-06-112733_891x644_scrot
2022-01-06-113410_884x656_scrot
2022-01-06-113426_874x650_scrot

**Comment by SmiteshP** [comment]
Yep. 
Just one question, any reason you choose to go for the method-name logo for a function? There is a function-name logo available too.

**Comment by gbprod** [comment]
Oh ! Didn't seen that ! Thanks, I've updated the PR

**Pull request merged**
