### PR TITLE
feat: add ability to set language specific icons and seperator

### PR DESCRIPTION
**Pull request by SmiteshP**
* allows setting symbols unique to a language
* and override existing symbols for languages

### CODE REVIEW

**Comment by SmiteshP** [comment]
@kassio Could you take a look at this PR? This should cover your use case. 😄

**Comment by SmiteshP** [comment]
@Hubro you can use this to add icons specific to YANG 😃

**Comment by kassio** [comment]
@SmiteshP thanks for working on that. Overall it looks good to me and I added some small suggestions for your consideration. 😄

**Comment by SmiteshP** [comment]
closing in favor of #29

**Pull request closed without merging**
